trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
# 1. Install 7zip
- powershell: |
    choco install 7zip -y
  displayName: 'Install 7zip'

# 2. Unzip the project
- powershell: |
    7z x "$(Build.SourcesDirectory)\popstar-external.zip" -o"$(Build.SourcesDirectory)\src"
  displayName: 'Extract zip'

# 3. Build the .sln
- task: VSBuild@1
  inputs:
    solution: 'src\popstar-external.sln'
    msbuildArgs: '/p:Configuration=Release'
    platform: 'x64'
    configuration: 'Release'
  displayName: 'Build Solution'

# 4. Publish final EXEs as artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\src'
    ArtifactName: 'build'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
